### ISSUE TITLE
[Zeta] Concurrency issue with group id.

### ISSUE THREAD

**Issue by zzxgzgz** [futurewei-cloud/alcor-control-agent#203]
**What happened:**

When running testcase to set up zeta ports, the testcase sometimes fails, here are some outputs:
```
Executing command: ovs-ofctl add-flow br-tun table=22,priority=50,dl_vlan=1,actions="strip_vlan,load:888->NXM_NX_TUN_ID[],group:2"
----------------
OFPT_ERROR (OF1.3) (xid=0x4): OFPGMFC_GROUP_EXISTS
OFPT_GROUP_MOD (OF1.3) (xid=0x4):
 ADD group_id=2,type=select,bucket=actions=set_field:192.168.20.103->tun_dst,set_field:82:83:c0:a8:14:67->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.110->tun_dst,set_field:82:83:c0:a8:14:6e->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.104->tun_dst,set_field:82:83:c0:a8:14:68->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.111->tun_dst,set_field:82:83:c0:a8:14:6f->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.105->tun_dst,set_field:82:83:c0:a8:14:69->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.112->tun_dst,set_field:82:83:c0:a8:14:70->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.101->tun_dst,set_field:82:83:c0:a8:14:65->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.106->tun_dst,set_field:82:83:c0:a8:14:6a->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.113->tun_dst,set_field:82:83:c0:a8:14:71->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.100->tun_dst,set_field:82:83:c0:a8:14:64->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.107->tun_dst,set_field:82:83:c0:a8:14:6b->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.114->tun_dst,set_field:82:83:c0:a8:14:72->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.108->tun_dst,set_field:82:83:c0:a8:14:6c->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.102->tun_dst,set_field:82:83:c0:a8:14:66->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.115->tun_dst,set_field:82:83:c0:a8:14:73->eth_dst,output:"vxlan-generic",bucket=actions=set_field:192.168.20.109->tun_dst,set_field:82:83:c0:a8:14:6d->eth_dst,output:"vxlan-generic"
```

We can see that the group_id is set to 2, when I was only running with only 1 VNI(888), hense group_id should only be 1. Please check the attached file for complete log.
[testcase_output.txt](https://github.com/futurewei-cloud/alcor-control-agent/files/5851380/testcase_output.txt)

**How to reproduce:**
Run the latest pseudo controller with this command:
`python3 run.py 10 10 0`

The test cases fails about 2 out of 5 times.

**Comment by er1cthe0ne** [comment]
Note that we faced similar issue in ACA due to the fact that multiple ports creation were done in multiple threads concurrently. We have the add a lock around finding and creating entries so that we don't have multiple thread finding nothing and creating redundent entries after. Please use locks carefully as it will slow things down.

Also note the below from the log file, looks like there are redundent entries added to the group rule:

ACA_Zeta_Programming::create_zeta_config <--- Exiting, overall_rc = 0
Executing command: ovs-ofctl -O OpenFlow13 mod-group br-tun group_id=2,type=select,bucket="set_field:192.168.20.111->tun_dst,mod_dl_dst:82:83:c0:a8:14:6f,output:vxlan-generic",bucket="set_field:192.168.20.111->tun_dst,mod_dl_dst:82:83:c0:a8:14:6f,output:vxlan-generic",bucket="set_field:192.168.20.112->tun_dst,mod_dl_dst:82:83:c0:a8:14:70,output:vxlan-generic",bucket="set_field:192.168.20.105->tun_dst,mod_dl_dst:82:83:c0:a8:14:69,output:vxlan-generic",bucket="set_field:192.168.20.103->tun_dst,mod_dl_dst:82:83:c0:a8:14:67,output:vxlan-generic",bucket="set_field:192.168.20.110->tun_dst,mod_dl_dst:82:83:c0:a8:14:6e,output:vxlan-generic",bucket="set_field:192.168.20.105->tun_dst,mod_dl_dst:82:83:c0:a8:14:69,output:vxlan-generic",bucket="set_field:192.168.20.106->tun_dst,mod_dl_dst:82:83:c0:a8:14:6a,output:vxlan-generic",bucket="set_field:192.168.20.112->tun_dst,mod_dl_dst:82:83:c0:a8:14:70,output:vxlan-generic",bucket="set_field:192.168.20.112->tun_dst,mod_dl_dst:82:83:c0:a8:14:70,output:vxlan-generic",bucket="set_field:192.168.20.104->tun_dst,mod_dl_dst:82:83:c0:a8:14:68,output:vxlan-generic",bucket="set_field:192.168.20.113->tun_dst,mod_dl_dst:82:83:c0:a8:14:71,output:vxlan-generic",bucket="set_field:192.168.20.101->tun_dst,mod_dl_dst:82:83:c0:a8:14:65,output:vxlan-generic",bucket="set_field:192.168.20.106->tun_dst,mod_dl_dst:82:83:c0:a8:14:6a,output:vxlan-generic",bucket="set_field:192.168.20.111->tun_dst,mod_dl_dst:82:83:c0:a8:14:6f,output:vxlan-generic",bucket="set_field:192.168.20.106->tun_dst,mod_dl_dst:82:83:c0:a8:14:6a,output:vxlan-generic",bucket="set_field:192.168.20.107->tun_dst,mod_dl_dst:82:83:c0:a8:14:6b,output:vxlan-generic",bucket="set_field:192.168.20.101->tun_dst,mod_dl_dst:82:83:c0:a8:14:65,output:vxlan-generic",bucket="set_field:192.168.20.113->tun_dst,mod_dl_dst:82:83:c0:a8:14:71,output:vxlan-generic",bucket="set_field:192.168.20.105->tun_dst,mod_dl_dst:82:83:c0:a8:14:69,output:vxlan-generic",bucket="set_field:192.168.20.101->tun_dst,mod_dl_dst:82:83:c0:a8:14:65,output:vxlan-generic",bucket="set_field:192.168.20.113->tun_dst,mod_dl_dst:82:83:c0:a8:14:71,output:vxlan-generic",bucket="set_field:192.168.20.114->tun_dst,mod_dl_dst:82:83:c0:a8:14:72,output:vxlan-generic",bucket="set_field:192.168.20.107->tun_dst,mod_dl_dst:82:83:c0:a8:14:6b,output:vxlan-generic",bucket="set_field:192.168.20.100->tun_dst,mod_dl_dst:82:83:c0:a8:14:64,output:vxlan-generic",bucket="set_field:192.168.20.112->tun_dst,mod_dl_dst:82:83:c0:a8:14:70,output:vxlan-generic",bucket="set_field:192.168.20.107->tun_dst,mod_dl_dst:82:83:c0:a8:14:6b,output:vxlan-generic",bucket="set_field:192.168.20.108->tun_dst,mod_dl_dst:82:83:c0:a8:14:6c,output:vxlan-generic",bucket="set_field:192.168.20.100->tun_dst,mod_dl_dst:82:83:c0:a8:14:64,output:vxlan-generic",bucket="set_field:192.168.20.114->tun_dst,mod_dl_dst:82:83:c0:a8:14:72,output:vxlan-generic",bucket="set_field:192.168.20.106->tun_dst,mod_dl_dst:82:83:c0:a8:14:6a,output:vxlan-generic",bucket="set_field:192.168.20.100->tun_dst,mod_dl_dst:82:83:c0:a8:14:64,output:vxlan-generic",bucket="set_field:192.168.20.102->tun_dst,mod_dl_dst:82:83:c0:a8:14:66,output:vxlan-generic",bucket="set_field:192.168.20.114->tun_dst,mod_dl_dst:82:83:c0:a8:14:72,output:vxlan-generic",bucket="set_field:192.168.20.115->tun_dst,mod_dl_dst:82:83:c0:a8:14:73,output:vxlan-generic",bucket="set_field:192.168.20.108->tun_dst,mod_dl_dst:82:83:c0:a8:14:6c,output:vxlan-generic",bucket="set_field:192.168.20.113->tun_dst,mod_dl_dst:82:83:c0:a8:14:71,output:vxlan-generic",bucket="set_field:192.168.20.108->tun_dst,mod_dl_dst:82:83:c0:a8:14:6c,output:vxlan-generic",bucket="set_field:192.168.20.109->tun_dst,mod_dl_dst:82:83:c0:a8:14:6d,output:vxlan-generic",bucket="set_field:192.168.20.102->tun_dst,mod_dl_dst:82:83:c0:a8:14:66,output:vxlan-generic",bucket="set_field:192.168.20.115->tun_dst,mod_dl_dst:82:83:c0:a8:14:73,output:vxlan-generic",bucket="set_field:192.168.20.107->tun_dst,mod_dl_dst:82:83:c0:a8:14:6b,output:vxlan-generic",bucket="set_field:192.168.20.102->tun_dst,mod_dl_dst:82:83:c0:a8:14:66,output:vxlan-generic",bucket="set_field:192.168.20.103->tun_dst,mod_dl_dst:82:83:c0:a8:14:67,output:vxlan-generic",bucket="set_field:192.168.20.115->tun_dst,mod_dl_dst:82:83:c0:a8:14:73,output:vxlan-generic",bucket="set_field:192.168.20.109->tun_dst,mod_dl_dst:82:83:c0:a8:14:6d,output:vxlan-generic",bucket="set_field:192.168.20.114->tun_dst,mod_dl_dst:82:83:c0:a8:14:72,output:vxlan-generic",bucket="set_field:192.168.20.109->tun_dst,mod_dl_dst:82:83:c0:a8:14:6d,output:vxlan-generic",bucket="set_field:192.168.20.110->tun_dst,mod_dl_dst:82:83:c0:a8:14:6e,output:vxlan-generic",bucket="set_field:192.168.20.103->tun_dst,mod_dl_dst:82:83:c0:a8:14:67,output:vxlan-generic",bucket="set_field:192.168.20.108->tun_dst,mod_dl_dst:82:83:c0:a8:14:6c,output:vxlan-generic",bucket="set_field:192.168.20.100->tun_dst,mod_dl_dst:82:83:c0:a8:14:64,output:vxlan-generic",bucket="set_field:192.168.20.103->tun_dst,mod_dl_dst:82:83:c0:a8:14:67,output:vxlan-generic",bucket="set_field:192.168.20.104->tun_dst,mod_dl_dst:82:83:c0:a8:14:68,output:vxlan-generic",bucket="set_field:192.168.20.101->tun_dst,mod_dl_dst:82:83:c0:a8:14:65,output:vxlan-generic",bucket="set_field:192.168.20.110->tun_dst,mod_dl_dst:82:83:c0:a8:14:6e,output:vxlan-generic",bucket="set_field:192.168.20.115->tun_dst,mod_dl_dst:82:83:c0:a8:14:73,output:vxlan-generic",bucket="set_field:192.168.20.110->tun_dst,mod_dl_dst:82:83:c0:a8:14:6e,output:vxlan-generic",bucket="set_field:192.168.20.111->tun_dst,mod_dl_dst:82:83:c0:a8:14:6f,output:vxlan-generic",bucket="set_field:192.168.20.104->tun_dst,mod_dl_dst:82:83:c0:a8:14:68,output:vxlan-generic",bucket="set_field:192.168.20.109->tun_dst,mod_dl_dst:82:83:c0:a8:14:6d,output:vxlan-generic",bucket="set_field:192.168.20.102->tun_dst,mod_dl_dst:82:83:c0:a8:14:66,output:vxlan-generic",bucket="set_field:192.168.20.104->tun_dst,mod_dl_dst:82:83:c0:a8:14:68,output:vxlan-generic",bucket="set_field:192.168.20.105->tun_dst,mod_dl_dst:82:83:c0:a8:14:69,output:vxlan-generic"

**Comment by zzxgzgz** [comment]
@zhangml 

A possible reason for this behavior can be found here:
https://github.com/futurewei-cloud/alcor-control-agent/blob/master/src/zeta/aca_zeta_programming.cpp#L197

According to the log attached above, multiple threads called this `create_zeta_config` funciton, and in this if statement, there's no lock used to protect it, and `created_entry` was called, in which a new zeta config was created with a new group id (2 in this case).

I suggest adding lock/unlock around this if statement, and test if it helps.

Thanks.
