### ISSUE TITLE
ACA unit test ovs_l2_test_cases.1_port_CREATE_DELETE failure

### ISSUE THREAD

**Issue by kiran1048** [futurewei-cloud/alcor-control-agent#217]
The unit test binary in ACA, built and located at:
./build/tests/aca_tests
fails the run.

The test "1_port_CREATE_DELETE failure" is defined at test/gtest/aca_test_ovs_l2.cpp

**Comment by er1cthe0ne** [comment]
the fix is to change the below function in aca_vlan_manager.cpp to the below, I have confirmed the test case failed before the change, and then passed after the change: 

int ACA_Vlan_Manager::delete_ovs_port(string /*vpc_id*/, string ovs_port,
                                      uint tunnel_id, ulong &culminative_time)
{
  ACA_LOG_DEBUG("%s", "ACA_Vlan_Manager::delete_ovs_port ---> Entering\n");

  vpc_table_entry *current_vpc_table_entry;
  int overall_rc = EXIT_SUCCESS;

  if (!_vpcs_table.find(tunnel_id, current_vpc_table_entry)) {
    ACA_LOG_ERROR("tunnel_id %u not found in vpc_table\n", tunnel_id);
    overall_rc = ENOENT;
  } else {
    current_vpc_table_entry->ovs_ports.erase(ovs_port);

    // clean up the vpc_table entry if there is no port assoicated
    if (current_vpc_table_entry->ovs_ports.empty()) {
      _vpcs_table.erase(tunnel_id);

      // also delete the rule assoicated with the VPC:
      // table 4 = incoming vxlan, allow incoming vxlan traffic matching tunnel_id
      // to stamp with internal vlan and deliver to br-int
      string cmd_string = "del-flows br-tun \"table=4, priority=1,tun_id=" +
                          to_string(tunnel_id) + "\" --strict";

      ACA_OVS_L2_Programmer::get_instance().execute_openflow_command(
              cmd_string, culminative_time, overall_rc);
    }
  }

  ACA_LOG_DEBUG("ACA_Vlan_Manager::delete_ovs_port <--- Exiting, overall_rc = %d\n", overall_rc);

  return overall_rc;
}
